<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class KasusSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        DB::table('kasus')->insert([
            [
                'kode_pengaduan' => 'KAS001',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 1,
                'jenis_masalah' => 'bullying',
                'urgensi' => 'segera',
                'dampak' => 'sedang',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Kasus bullying di area kampus oleh beberapa mahasiswa.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Teknik',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kode_pengaduan' => 'KAS002',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 2,
                'jenis_masalah' => 'kekerasan seksual',
                'urgensi' => 'segera',
                'dampak' => 'sangat besar',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Kasus kekerasan seksual di area kampus yang melibatkan pihak dosen.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Teknik',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kode_pengaduan' => 'KAS003',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 3,
                'jenis_masalah' => 'pelecehan verbal',
                'urgensi' => 'dalam beberapa hari',
                'dampak' => 'sedang',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Kasus pelecehan verbal oleh senior kepada junior.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Teknik',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kode_pengaduan' => 'KAS004',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 4,
                'jenis_masalah' => 'diskriminasi',
                'urgensi' => 'tidak mendesak',
                'dampak' => 'kecil',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Diskriminasi dalam pembagian tugas kuliah.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Teknik',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kode_pengaduan' => 'KAS005',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 5,
                'jenis_masalah' => 'cyberbullying',
                'urgensi' => 'segera',
                'dampak' => 'sangat besar',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Serangan cyberbullying melalui media sosial terhadap pelapor.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Teknik',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kode_pengaduan' => 'KAS006',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 6,
                'jenis_masalah' => 'lainnya',
                'urgensi' => 'dalam beberapa hari',
                'dampak' => 'sedang',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Laporan tentang ketidakadilan dalam penilaian mata kuliah.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Ilmu Sosial dan Ilmu Politik',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kode_pengaduan' => 'KAS007',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 7,
                'jenis_masalah' => 'bullying',
                'urgensi' => 'segera',
                'dampak' => 'sedang',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Bullying yang terjadi di dalam ruang kuliah.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Kedokteran dan Ilmu Kesehatan',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kode_pengaduan' => 'KAS008',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 8,
                'jenis_masalah' => 'kekerasan seksual',
                'urgensi' => 'segera',
                'dampak' => 'sangat besar',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Tindak kekerasan seksual di lingkungan kampus.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Ekonomi dan Bisnis',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kode_pengaduan' => 'KAS009',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 9,
                'jenis_masalah' => 'pelecehan verbal',
                'urgensi' => 'dalam beberapa hari',
                'dampak' => 'kecil',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Pelecehan verbal oleh teman satu jurusan.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Hukum',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'kode_pengaduan' => 'KAS010',
                'id_kemahasiswaan' => null,
                'id_pelapor' => 10,
                'jenis_masalah' => 'diskriminasi',
                'urgensi' => 'tidak mendesak',
                'dampak' => 'sedang',
                'status_pengaduan' => 'perlu dikonfirmasi',
                'tanggal_konfirmasi' => null,
                'tanggal_pengaduan' => $now->toDateString(),
                'deskripsi_kasus' => 'Diskriminasi dalam proses rekrutmen organisasi kampus.',
                'bukti_kasus' => 'public/assets/img/bukti.png',
                'asal_fakultas' => 'Pertanian',
                'penangan_kasus' => null,
                'catatan_penanganan' => null,
                'created_at' => $now,
                'updated_at' => $now
            ],
        ]);
    }
}
